export interface CaseDropTable {
  common: number;
  uncommon: number;
  rare: number;
  epic: number;
  legendary: number;
  unique: number;
}

export interface CaseDefinition {
  id: string;
  name: string;
  emoji: string;
  description: string;
  priceChips: number;
  collectionFilter: string[] | null; // null = any collection; array = only these collectionIds
  dropTable: CaseDropTable; // weights (sum doesn't need to be 100; normalized at runtime)
}

export const CASES: CaseDefinition[] = [
  // ─── TIER 1 — Starter (50–150 chips) ─────────────────────────────────────
  {
    id: "lucky_starter",
    name: "Lucky Starter",
    emoji: "🎁",
    description: "The perfect first case for newcomers — packed with common goodies and a sprinkle of luck.",
    priceChips: 50,
    collectionFilter: null,
    dropTable: { common: 68, uncommon: 26, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "casino_basics",
    name: "Casino Basics",
    emoji: "🎰",
    description: "A no-frills intro case with solid common drops and occasional uncommon surprises.",
    priceChips: 60,
    collectionFilter: null,
    dropTable: { common: 70, uncommon: 25, rare: 4, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "lucky_charms_box",
    name: "Lucky Charms Box",
    emoji: "🍀",
    description: "Carry a little fortune with you — this box is brimming with charmed common items.",
    priceChips: 75,
    collectionFilter: null,
    dropTable: { common: 67, uncommon: 27, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "space_intro",
    name: "Space Intro",
    emoji: "🚀",
    description: "Launch your collection journey into the cosmos with this affordable starter pack.",
    priceChips: 80,
    collectionFilter: null,
    dropTable: { common: 69, uncommon: 25, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "street_box",
    name: "Street Box",
    emoji: "🏙️",
    description: "Born on the pavement — a gritty urban case full of everyday street-style drops.",
    priceChips: 90,
    collectionFilter: null,
    dropTable: { common: 66, uncommon: 28, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "nature_bundle",
    name: "Nature Bundle",
    emoji: "🌿",
    description: "Breathe fresh air into your collection with this nature-themed beginner bundle.",
    priceChips: 100,
    collectionFilter: null,
    dropTable: { common: 68, uncommon: 26, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "mystery_beginner",
    name: "Mystery Beginner",
    emoji: "❓",
    description: "What's inside? Even we aren't sure — open it and let fate decide for you.",
    priceChips: 110,
    collectionFilter: null,
    dropTable: { common: 65, uncommon: 28, rare: 6, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "coin_flip_box",
    name: "Coin Flip Box",
    emoji: "🪙",
    description: "Heads or tails? Either way you walk away with something from this classic starter case.",
    priceChips: 120,
    collectionFilter: null,
    dropTable: { common: 67, uncommon: 27, rare: 5, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "fortune_seeker",
    name: "Fortune Seeker",
    emoji: "🔮",
    description: "For those who believe destiny rewards the bold — a beginner case with heart.",
    priceChips: 135,
    collectionFilter: null,
    dropTable: { common: 66, uncommon: 27, rare: 6, epic: 1, legendary: 0, unique: 0 },
  },
  {
    id: "rookie_case",
    name: "Rookie Case",
    emoji: "⭐",
    description: "Every legend starts somewhere — your journey begins with this rookie case.",
    priceChips: 150,
    collectionFilter: null,
    dropTable: { common: 65, uncommon: 28, rare: 6, epic: 1, legendary: 0, unique: 0 },
  },

  // ─── TIER 2 — Standard (175–400 chips) ───────────────────────────────────
  {
    id: "card_collector",
    name: "Card Collector",
    emoji: "🃏",
    description: "Deal yourself in — this case favours sharp uncommons with a chance at rare card art.",
    priceChips: 175,
    collectionFilter: null,
    dropTable: { common: 25, uncommon: 50, rare: 20, epic: 5, legendary: 0, unique: 0 },
  },
  {
    id: "cyber_pack",
    name: "Cyber Pack",
    emoji: "💻",
    description: "Jack into the grid and pull neon-lit uncommons from this cyberpunk-themed pack.",
    priceChips: 200,
    collectionFilter: null,
    dropTable: { common: 28, uncommon: 47, rare: 21, epic: 4, legendary: 0, unique: 0 },
  },
  {
    id: "ancient_finder",
    name: "Ancient Finder",
    emoji: "🏺",
    description: "Dig through centuries of history and unearth uncommon relics from the ancient world.",
    priceChips: 225,
    collectionFilter: ["ancient_fortune"],
    dropTable: { common: 22, uncommon: 52, rare: 22, epic: 4, legendary: 0, unique: 0 },
  },
  {
    id: "royal_court",
    name: "Royal Court",
    emoji: "👑",
    description: "Step into the throne room where uncommon royalty and rare treasures await.",
    priceChips: 250,
    collectionFilter: null,
    dropTable: { common: 24, uncommon: 49, rare: 23, epic: 4, legendary: 0, unique: 0 },
  },
  {
    id: "gamblers_box",
    name: "Gambler's Box",
    emoji: "🎲",
    description: "Ante up — this box rewards the bold with a healthy mix of uncommon and rare prizes.",
    priceChips: 275,
    collectionFilter: null,
    dropTable: { common: 20, uncommon: 55, rare: 20, epic: 5, legendary: 0, unique: 0 },
  },
  {
    id: "golden_collection",
    name: "Golden Collection",
    emoji: "🥇",
    description: "Not quite the top shelf, but this golden case shines brighter than most standard packs.",
    priceChips: 300,
    collectionFilter: null,
    dropTable: { common: 23, uncommon: 50, rare: 23, epic: 4, legendary: 0, unique: 0 },
  },
  {
    id: "casino_royale_box",
    name: "Casino Royale Box",
    emoji: "🎩",
    description: "Dressed to impress — pull exclusive casino_royale-collection drops from this suave case.",
    priceChips: 325,
    collectionFilter: ["casino_royale"],
    dropTable: { common: 21, uncommon: 53, rare: 22, epic: 4, legendary: 0, unique: 0 },
  },
  {
    id: "street_king_box",
    name: "Street King Box",
    emoji: "👟",
    description: "Rule the block — a street-culture case loaded with rare urban style drops.",
    priceChips: 350,
    collectionFilter: null,
    dropTable: { common: 26, uncommon: 45, rare: 24, epic: 5, legendary: 0, unique: 0 },
  },
  {
    id: "cosmic_explorer",
    name: "Cosmic Explorer",
    emoji: "🌌",
    description: "Chart unexplored star systems and return with uncommon cosmic treasures.",
    priceChips: 375,
    collectionFilter: null,
    dropTable: { common: 22, uncommon: 50, rare: 23, epic: 5, legendary: 0, unique: 0 },
  },
  {
    id: "nature_rare_box",
    name: "Nature Rare Box",
    emoji: "🦋",
    description: "Deep in the forest, rare creatures emerge — find them in this nature collector's case.",
    priceChips: 400,
    collectionFilter: null,
    dropTable: { common: 20, uncommon: 50, rare: 25, epic: 5, legendary: 0, unique: 0 },
  },

  // ─── TIER 3 — Premium (450–900 chips) ────────────────────────────────────
  {
    id: "rare_finds",
    name: "Rare Finds",
    emoji: "💎",
    description: "Curated for collectors who know quality — rare drops dominate this premium selection.",
    priceChips: 450,
    collectionFilter: null,
    dropTable: { common: 8, uncommon: 36, rare: 45, epic: 10, legendary: 1, unique: 0 },
  },
  {
    id: "high_roller_box",
    name: "High Roller Box",
    emoji: "🎰",
    description: "Only the high rollers open this — a premium case with epic-tier potential.",
    priceChips: 500,
    collectionFilter: null,
    dropTable: { common: 6, uncommon: 38, rare: 43, epic: 12, legendary: 1, unique: 0 },
  },
  {
    id: "epic_hunter",
    name: "Epic Hunter",
    emoji: "🏹",
    description: "Track down rare and epic game with this hunter's premium case — the thrill is real.",
    priceChips: 550,
    collectionFilter: null,
    dropTable: { common: 7, uncommon: 34, rare: 46, epic: 12, legendary: 1, unique: 0 },
  },
  {
    id: "ancient_vault",
    name: "Ancient Vault",
    emoji: "🏛️",
    description: "Sealed for millennia, this ancient vault unlocks rare and epic relics from lost civilizations.",
    priceChips: 600,
    collectionFilter: ["ancient_fortune"],
    dropTable: { common: 5, uncommon: 35, rare: 48, epic: 11, legendary: 1, unique: 0 },
  },
  {
    id: "cyber_elite",
    name: "Cyber Elite",
    emoji: "⚡",
    description: "Top-tier tech drops for the digital elite — rare and epic cyber items await inside.",
    priceChips: 650,
    collectionFilter: null,
    dropTable: { common: 6, uncommon: 33, rare: 47, epic: 13, legendary: 1, unique: 0 },
  },
  {
    id: "legend_seeker",
    name: "Legend Seeker",
    emoji: "🗺️",
    description: "Follow the map to glory — this premium case hints at legendary drops just beyond the horizon.",
    priceChips: 700,
    collectionFilter: ["legends"],
    dropTable: { common: 5, uncommon: 31, rare: 50, epic: 13, legendary: 1, unique: 0 },
  },
  {
    id: "galaxy_box",
    name: "Galaxy Box",
    emoji: "🌠",
    description: "Pull star-forged items from the furthest reaches of the galaxy in this premium cosmic case.",
    priceChips: 750,
    collectionFilter: null,
    dropTable: { common: 7, uncommon: 32, rare: 48, epic: 12, legendary: 1, unique: 0 },
  },
  {
    id: "darkness_case",
    name: "Darkness Case",
    emoji: "🌑",
    description: "Peer into the void and claim the dark, rare artifacts that dwell within.",
    priceChips: 800,
    collectionFilter: null,
    dropTable: { common: 5, uncommon: 30, rare: 50, epic: 14, legendary: 1, unique: 0 },
  },
  {
    id: "premium_mystery",
    name: "Premium Mystery",
    emoji: "🔮",
    description: "Even our oracles can't predict this one — a premium case veiled in thrilling uncertainty.",
    priceChips: 850,
    collectionFilter: null,
    dropTable: { common: 6, uncommon: 34, rare: 45, epic: 14, legendary: 1, unique: 0 },
  },
  {
    id: "dragons_eye",
    name: "Dragon's Eye",
    emoji: "🐉",
    description: "Gaze into the dragon's eye and claim the rare and epic hoard it guards.",
    priceChips: 900,
    collectionFilter: null,
    dropTable: { common: 5, uncommon: 30, rare: 50, epic: 14, legendary: 1, unique: 0 },
  },

  // ─── TIER 4 — Elite (1000–3000 chips) ────────────────────────────────────
  {
    id: "elite_collection",
    name: "Elite Collection",
    emoji: "🏆",
    description: "Reserved for the serious collector — epic and legendary drops fill this elite case.",
    priceChips: 1000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 14, rare: 46, epic: 33, legendary: 7, unique: 0 },
  },
  {
    id: "ancient_epic",
    name: "Ancient Epic",
    emoji: "⚗️",
    description: "Only epic-grade relics survive the test of time — open this ancient treasury to claim them.",
    priceChips: 1250,
    collectionFilter: ["ancient_fortune"],
    dropTable: { common: 0, uncommon: 12, rare: 48, epic: 34, legendary: 6, unique: 0 },
  },
  {
    id: "legendary_hunt",
    name: "Legendary Hunt",
    emoji: "🦁",
    description: "The hunt for legendary prey begins here — stalk your quarry through epic-tier wilderness.",
    priceChips: 1500,
    collectionFilter: ["legends"],
    dropTable: { common: 0, uncommon: 11, rare: 44, epic: 35, legendary: 10, unique: 0 },
  },
  {
    id: "casino_legends",
    name: "Casino Legends",
    emoji: "🎴",
    description: "Only the greatest players open Casino Legends — epic drops and legendary wins await.",
    priceChips: 1750,
    collectionFilter: ["casino_royale"],
    dropTable: { common: 0, uncommon: 10, rare: 45, epic: 36, legendary: 9, unique: 0 },
  },
  {
    id: "mythical_vault",
    name: "Mythical Vault",
    emoji: "🗝️",
    description: "Unlock the vault of myth and claim epic-to-legendary items forged by gods and monsters.",
    priceChips: 2000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 13, rare: 42, epic: 37, legendary: 8, unique: 0 },
  },
  {
    id: "dragons_lair",
    name: "Dragon's Lair",
    emoji: "🔥",
    description: "Brave the flames and plunder the lair — epic and legendary dragon treasures await the bold.",
    priceChips: 2250,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 10, rare: 43, epic: 38, legendary: 9, unique: 0 },
  },
  {
    id: "supreme_box",
    name: "Supreme Box",
    emoji: "💠",
    description: "Supreme quality, supreme rewards — an elite box stacked with the game's finest drops.",
    priceChips: 2500,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 11, rare: 41, epic: 40, legendary: 8, unique: 0 },
  },
  {
    id: "titan_case",
    name: "Titan Case",
    emoji: "🗿",
    description: "Built by titans, filled with titan-level loot — epic and legendary items tower inside.",
    priceChips: 2750,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 10, rare: 40, epic: 40, legendary: 10, unique: 0 },
  },
  {
    id: "gods_vault",
    name: "God's Vault",
    emoji: "⛩️",
    description: "Mortals rarely glimpse inside a god's vault — your epic-and-legendary haul awaits.",
    priceChips: 2900,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 10, rare: 38, epic: 42, legendary: 10, unique: 0 },
  },
  {
    id: "ultimate_hunt",
    name: "Ultimate Hunt",
    emoji: "🎯",
    description: "The ultimate prize awaits those who dare — epic-and-legendary drops at every turn.",
    priceChips: 3000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 10, rare: 37, epic: 43, legendary: 10, unique: 0 },
  },

  // ─── TIER 5 — Legendary (4000–15000 chips) ───────────────────────────────
  {
    id: "titan_box",
    name: "Titan Box",
    emoji: "🌋",
    description: "Only titans dare open this — legendary and unique drops lurk inside its colossal frame.",
    priceChips: 4000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 18, epic: 50, legendary: 27, unique: 5 },
  },
  {
    id: "god_chest",
    name: "God Chest",
    emoji: "☀️",
    description: "A chest blessed by the gods themselves — expect legendary power with every opening.",
    priceChips: 5000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 15, epic: 52, legendary: 28, unique: 5 },
  },
  {
    id: "ancient_omega",
    name: "Ancient Omega",
    emoji: "🌀",
    description: "The final word in ancient power — legendary and unique relics of immense rarity await.",
    priceChips: 6000,
    collectionFilter: ["ancient_fortune"],
    dropTable: { common: 0, uncommon: 0, rare: 12, epic: 52, legendary: 30, unique: 6 },
  },
  {
    id: "celestial_vault",
    name: "Celestial Vault",
    emoji: "🌙",
    description: "Forged in the heart of dying stars — open the celestial vault for cosmic legendary loot.",
    priceChips: 7500,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 13, epic: 48, legendary: 33, unique: 6 },
  },
  {
    id: "olympus_chest",
    name: "Olympus Chest",
    emoji: "⚡",
    description: "Sent down from Mount Olympus — legendary items forged by divine hands rest inside.",
    priceChips: 8500,
    collectionFilter: ["legends"],
    dropTable: { common: 0, uncommon: 0, rare: 11, epic: 47, legendary: 35, unique: 7 },
  },
  {
    id: "cosmos_prime",
    name: "Cosmos Prime",
    emoji: "🪐",
    description: "The universe compressed into a single case — unique items of cosmic significance await.",
    priceChips: 10000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 10, epic: 48, legendary: 34, unique: 8 },
  },
  {
    id: "shadow_vault",
    name: "Shadow Vault",
    emoji: "🕳️",
    description: "Hidden in the darkest corner of the collection — unique shadow-forged items emerge from within.",
    priceChips: 11000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 12, epic: 46, legendary: 35, unique: 7 },
  },
  {
    id: "infinity_box",
    name: "Infinity Box",
    emoji: "♾️",
    description: "Infinite value in finite form — this box contains legendary and unique items without equal.",
    priceChips: 12500,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 10, epic: 45, legendary: 37, unique: 8 },
  },
  {
    id: "sovereign_chest",
    name: "Sovereign Chest",
    emoji: "👑",
    description: "The sovereign's private treasury — legendary and unique relics reserved for true rulers.",
    priceChips: 13500,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 10, epic: 43, legendary: 40, unique: 7 },
  },
  {
    id: "the_grand_case",
    name: "The Grand Case",
    emoji: "🏅",
    description: "The pinnacle of the collection — only the wealthiest dare open The Grand Case.",
    priceChips: 15000,
    collectionFilter: null,
    dropTable: { common: 0, uncommon: 0, rare: 10, epic: 40, legendary: 42, unique: 8 },
  },
];
