export interface NftPower {
  type: "chips_bonus" | "xp_bonus" | "jackpot_entry" | "free_spin" | "multiplier_boost";
  label: string;
  value: number;
  description: string;
}

export interface NftTemplate {
  id: string;
  name: string;
  collection: string;
  collectionId: string;
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary" | "unique";
  emoji: string;
  description: string;
  priceChips: number;
  supply: number; // -1 = unlimited
  power: NftPower | null;
  tags: string[];
}

export const NFT_CATALOG: NftTemplate[] = [
  // ══════════════════════════════════════════════════════════
  // CASINO ROYALE — cards, chips, dice
  // ══════════════════════════════════════════════════════════
  {
    id: "cr_spade_common",
    name: "Ace of Spades",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "♠️",
    description: "The classic Ace of Spades. Every collection starts here.",
    priceChips: 10,
    supply: -1,
    power: null,
    tags: ["card", "spade", "ace", "classic"],
  },
  {
    id: "cr_heart_common",
    name: "Ace of Hearts",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "♥️",
    description: "Play with heart. The Ace of Hearts brings passion to the table.",
    priceChips: 10,
    supply: -1,
    power: null,
    tags: ["card", "heart", "ace", "classic"],
  },
  {
    id: "cr_diamond_common",
    name: "Ace of Diamonds",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "♦️",
    description: "Sparkling and sharp. The Ace of Diamonds.",
    priceChips: 10,
    supply: -1,
    power: null,
    tags: ["card", "diamond", "ace", "classic"],
  },
  {
    id: "cr_club_common",
    name: "Ace of Clubs",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "♣️",
    description: "Lucky clover-shaped ace. Favored by card sharks.",
    priceChips: 10,
    supply: -1,
    power: null,
    tags: ["card", "club", "ace", "classic"],
  },
  {
    id: "cr_red_chip",
    name: "Red Chip",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "🔴",
    description: "A standard $5 casino chip. The starting point of every big win.",
    priceChips: 8,
    supply: -1,
    power: null,
    tags: ["chip", "casino", "red"],
  },
  {
    id: "cr_blue_chip",
    name: "Blue Chip",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "🔵",
    description: "A crisp $10 blue casino chip. Reliable and classic.",
    priceChips: 8,
    supply: -1,
    power: null,
    tags: ["chip", "casino", "blue"],
  },
  {
    id: "cr_dice_pair",
    name: "Lucky Pair",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "🎲",
    description: "A matched pair of ivory dice. Shake 'em and believe.",
    priceChips: 12,
    supply: -1,
    power: null,
    tags: ["dice", "luck", "pair"],
  },
  {
    id: "cr_roulette_ball",
    name: "Roulette Ball",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "common",
    emoji: "⚪",
    description: "A tiny ivory ball. The fate of millions spins around it.",
    priceChips: 8,
    supply: -1,
    power: null,
    tags: ["roulette", "ball", "spin", "casino"],
  },
  {
    id: "cr_joker_uncommon",
    name: "Golden Joker",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "uncommon",
    emoji: "🃏",
    description: "The wild card. The Joker changes every hand it touches.",
    priceChips: 35,
    supply: -1,
    power: { type: "free_spin", label: "Free Spin", value: 25, description: "Activate for a free +25 chip spin bonus" },
    tags: ["card", "joker", "wild", "bonus"],
  },
  {
    id: "cr_black_chip",
    name: "Black Chip",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "uncommon",
    emoji: "⚫",
    description: "The $100 black casino chip. Reserved for serious players.",
    priceChips: 45,
    supply: -1,
    power: null,
    tags: ["chip", "casino", "black", "prestige"],
  },
  {
    id: "cr_king_spades",
    name: "King of Spades",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "uncommon",
    emoji: "🂮",
    description: "The suicide king. A face card that commands respect at every table.",
    priceChips: 40,
    supply: -1,
    power: null,
    tags: ["card", "king", "spades", "face card"],
  },
  {
    id: "cr_queen_hearts",
    name: "Queen of Hearts",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "uncommon",
    emoji: "🂽",
    description: "Off with your chips! The Queen rules with an iron fist and a velvet glove.",
    priceChips: 40,
    supply: -1,
    power: null,
    tags: ["card", "queen", "hearts", "face card"],
  },
  {
    id: "cr_poker_table",
    name: "Felt Poker Table",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "uncommon",
    emoji: "🎯",
    description: "Green felt, mahogany rails. Where fortunes are made and lost.",
    priceChips: 50,
    supply: -1,
    power: null,
    tags: ["table", "poker", "felt", "casino"],
  },
  {
    id: "cr_royal_flush",
    name: "Royal Flush",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "rare",
    emoji: "👑",
    description: "The unbeatable hand. A Royal Flush NFT radiates pure poker energy.",
    priceChips: 200,
    supply: -1,
    power: { type: "chips_bonus", label: "Royal Bonus", value: 150, description: "Activate for an instant +150 chip bonus" },
    tags: ["card", "poker", "flush", "royal", "premium"],
  },
  {
    id: "cr_gold_chip_stack",
    name: "Gold Chip Stack",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "rare",
    emoji: "🥇",
    description: "A towering stack of premium gold chips worth 10,000 at the casino.",
    priceChips: 175,
    supply: -1,
    power: { type: "xp_bonus", label: "Prestige XP", value: 200, description: "Activate for +200 XP" },
    tags: ["chip", "gold", "stack", "premium"],
  },
  {
    id: "cr_diamond_dice",
    name: "Diamond Dice",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "rare",
    emoji: "💎",
    description: "Carved from a single diamond. These dice never roll cold.",
    priceChips: 250,
    supply: -1,
    power: { type: "multiplier_boost", label: "Diamond Roll", value: 100, description: "Activate for a +100 chip multiplier boost" },
    tags: ["dice", "diamond", "luxury", "premium"],
  },
  {
    id: "cr_slot_seven",
    name: "Triple Seven",
    collection: "Casino Royale",
    collectionId: "casino_royale",
    rarity: "rare",
    emoji: "7️⃣",
    description: "777. The holy trinity of slots. Whoever holds this always feels the jackpot near.",
    priceChips: 150,
    supply: -1,
    power: { type: "free_spin", label: "Lucky 7 Spin", value: 77, description: "Activate for a +77 chip lucky spin" },
    tags: ["seven", "777", "slots", "jackpot", "lucky"],
  },

  // ══════════════════════════════════════════════════════════
  // LUCKY CHARMS — horseshoe, clover, lucky cat
  // ══════════════════════════════════════════════════════════
  {
    id: "lc_horseshoe_common",
    name: "Iron Horseshoe",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "common",
    emoji: "🧲",
    description: "Hang it over the door, carry it to the table. Luck follows.",
    priceChips: 9,
    supply: -1,
    power: null,
    tags: ["horseshoe", "luck", "charm"],
  },
  {
    id: "lc_clover_common",
    name: "Four-Leaf Clover",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "common",
    emoji: "🍀",
    description: "Found in a field in Ireland. Genuine luck guaranteed.",
    priceChips: 9,
    supply: -1,
    power: null,
    tags: ["clover", "luck", "irish"],
  },
  {
    id: "lc_rabbit_foot",
    name: "Rabbit's Foot",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "common",
    emoji: "🐇",
    description: "A classic gambler's talisman. Old-school luck.",
    priceChips: 7,
    supply: -1,
    power: null,
    tags: ["rabbit", "luck", "classic"],
  },
  {
    id: "lc_dice_charm",
    name: "Dice Charm",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "common",
    emoji: "🎲",
    description: "Tiny gold dice on a chain. Always shows sixes in your pocket.",
    priceChips: 12,
    supply: -1,
    power: null,
    tags: ["dice", "charm", "luck", "jewelry"],
  },
  {
    id: "lc_lucky_cat",
    name: "Lucky Cat",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "uncommon",
    emoji: "🐱",
    description: "Maneki-neko waving from the entrance. Fortune flows in.",
    priceChips: 30,
    supply: -1,
    power: { type: "xp_bonus", label: "Fortune Cat", value: 100, description: "Activate for +100 XP" },
    tags: ["cat", "luck", "japanese", "maneki"],
  },
  {
    id: "lc_golden_horseshoe",
    name: "Golden Horseshoe",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "uncommon",
    emoji: "🏇",
    description: "A pure gold horseshoe from the legendary champion steed Aura.",
    priceChips: 50,
    supply: -1,
    power: { type: "free_spin", label: "Lucky Spin", value: 30, description: "Activate for a +30 chip free spin bonus" },
    tags: ["horseshoe", "gold", "luck", "premium"],
  },
  {
    id: "lc_wishbone",
    name: "Golden Wishbone",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "uncommon",
    emoji: "🦴",
    description: "Make a wish and pull. The bigger half wins.",
    priceChips: 28,
    supply: -1,
    power: null,
    tags: ["wishbone", "luck", "wish"],
  },
  {
    id: "lc_evil_eye",
    name: "Evil Eye Amulet",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "uncommon",
    emoji: "🧿",
    description: "Wards off bad luck. Blue glass from the Turkish coast.",
    priceChips: 35,
    supply: -1,
    power: null,
    tags: ["evil eye", "amulet", "protection", "turkish"],
  },
  {
    id: "lc_lucky_number_7",
    name: "Lucky Number 7",
    collection: "Lucky Charms",
    collectionId: "lucky_charms",
    rarity: "uncommon",
    emoji: "7️⃣",
    description: "The luckiest number in the world. Framed and ready to hang.",
    priceChips: 32,
    supply: -1,
    power: { type: "xp_bonus", label: "Lucky Seven XP", value: 70, description: "Activate for +70 XP" },
    tags: ["seven", "lucky", "charm", "number"],
  },

  // ══════════════════════════════════════════════════════════
  // HIGH ROLLER — champagne, cars, yachts
  // ══════════════════════════════════════════════════════════
  {
    id: "hr_champagne",
    name: "Moët Moment",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "uncommon",
    emoji: "🍾",
    description: "Pop the champagne. You've earned a seat at the high roller table.",
    priceChips: 75,
    supply: -1,
    power: null,
    tags: ["champagne", "luxury", "celebration"],
  },
  {
    id: "hr_gold_watch",
    name: "Gold Chronograph",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "uncommon",
    emoji: "⌚",
    description: "Swiss-made. 18-karat gold case. Time is money — this is both.",
    priceChips: 110,
    supply: -1,
    power: null,
    tags: ["watch", "gold", "swiss", "luxury"],
  },
  {
    id: "hr_caviar",
    name: "Beluga Caviar",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "uncommon",
    emoji: "🫦",
    description: "The rarest caviar from the Caspian Sea. Only for those who've already won.",
    priceChips: 85,
    supply: -1,
    power: null,
    tags: ["caviar", "luxury", "food", "beluga"],
  },
  {
    id: "hr_diamond_ring",
    name: "Champion's Ring",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "uncommon",
    emoji: "💍",
    description: "Only worn by winners. A diamond-encrusted symbol of the high roller.",
    priceChips: 90,
    supply: -1,
    power: null,
    tags: ["ring", "diamond", "winner", "luxury"],
  },
  {
    id: "hr_sports_car",
    name: "Crimson Supercar",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "rare",
    emoji: "🏎️",
    description: "0–60 in 2.4 seconds. A symbol of speed and success.",
    priceChips: 350,
    supply: -1,
    power: { type: "chips_bonus", label: "Fast Money", value: 200, description: "Activate for an instant +200 chip boost" },
    tags: ["car", "speed", "luxury", "sports"],
  },
  {
    id: "hr_yacht",
    name: "Private Yacht",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "rare",
    emoji: "⛵",
    description: "Anchored in Monaco harbor. The VIP life afloat.",
    priceChips: 400,
    supply: -1,
    power: { type: "xp_bonus", label: "Yacht Club XP", value: 350, description: "Activate for +350 XP" },
    tags: ["yacht", "luxury", "monaco", "sea"],
  },
  {
    id: "hr_penthouse",
    name: "Penthouse Suite",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "rare",
    emoji: "🏙️",
    description: "Floor 90. City lights stretch to the horizon. This is the life.",
    priceChips: 300,
    supply: -1,
    power: null,
    tags: ["penthouse", "luxury", "city", "suite"],
  },
  {
    id: "hr_limousine",
    name: "Stretch Limousine",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "rare",
    emoji: "🚗",
    description: "24 feet of luxury. The casino sends it to pick you up when you're this high a roller.",
    priceChips: 280,
    supply: -1,
    power: null,
    tags: ["limo", "car", "luxury", "transport"],
  },
  {
    id: "hr_private_jet",
    name: "Private Jet",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "epic",
    emoji: "✈️",
    description: "No boarding pass needed. Just a net worth that qualifies.",
    priceChips: 2500,
    supply: 500,
    power: { type: "multiplier_boost", label: "Jet Boost", value: 500, description: "Activate for a +500 chip multiplier boost" },
    tags: ["jet", "luxury", "travel", "elite"],
  },
  {
    id: "hr_mega_yacht",
    name: "Mega Yacht Aurora",
    collection: "High Roller",
    collectionId: "high_roller",
    rarity: "epic",
    emoji: "🚢",
    description: "300 feet of pure luxury. The Aurora sails where others can only dream.",
    priceChips: 3000,
    supply: 500,
    power: { type: "jackpot_entry", label: "Jackpot Pass", value: 1, description: "Activate to register a jackpot entry" },
    tags: ["yacht", "mega", "luxury", "elite", "ocean"],
  },

  // ══════════════════════════════════════════════════════════
  // COSMIC CASINO — space, galaxy, planets
  // ══════════════════════════════════════════════════════════
  {
    id: "cc_shooting_star",
    name: "Shooting Star",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "common",
    emoji: "🌠",
    description: "Make a wish before it fades. Cosmic luck is real.",
    priceChips: 12,
    supply: -1,
    power: null,
    tags: ["star", "space", "wish", "cosmic"],
  },
  {
    id: "cc_moon_chip",
    name: "Moon Chip",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "common",
    emoji: "🌙",
    description: "Minted on the dark side. Lunar energy packed in a chip.",
    priceChips: 15,
    supply: -1,
    power: null,
    tags: ["moon", "chip", "cosmic", "space"],
  },
  {
    id: "cc_comet",
    name: "Lucky Comet",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "common",
    emoji: "☄️",
    description: "Passes every 76 years. Today is your lucky day.",
    priceChips: 14,
    supply: -1,
    power: null,
    tags: ["comet", "luck", "cosmic", "rare event"],
  },
  {
    id: "cc_asteroid",
    name: "Lucky Asteroid",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "common",
    emoji: "🪨",
    description: "A fragment of space rock that survived the journey. From 93 million miles away.",
    priceChips: 18,
    supply: -1,
    power: null,
    tags: ["asteroid", "space rock", "cosmic", "fragment"],
  },
  {
    id: "cc_alien_dice",
    name: "Alien Dice",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "uncommon",
    emoji: "👽",
    description: "17 sides. Non-Euclidean probability. Intergalactic gaming.",
    priceChips: 55,
    supply: -1,
    power: null,
    tags: ["alien", "dice", "extraterrestrial", "cosmic"],
  },
  {
    id: "cc_planet_saturn",
    name: "Saturn's Ring",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "uncommon",
    emoji: "🪐",
    description: "The ringed giant. Rare minerals and cosmic beauty fused.",
    priceChips: 60,
    supply: -1,
    power: { type: "xp_bonus", label: "Cosmic XP", value: 120, description: "Activate for +120 XP" },
    tags: ["saturn", "planet", "ring", "cosmic"],
  },
  {
    id: "cc_nebula",
    name: "Nebula Cloud",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "uncommon",
    emoji: "🌌",
    description: "A trillion stars born from one cloud of gas. You hold the cosmos.",
    priceChips: 70,
    supply: -1,
    power: null,
    tags: ["nebula", "galaxy", "space", "cosmic"],
  },
  {
    id: "cc_galaxy_chip",
    name: "Galaxy Chip",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "uncommon",
    emoji: "🌀",
    description: "Swirling galactic patterns on a translucent chip. From another dimension.",
    priceChips: 65,
    supply: -1,
    power: null,
    tags: ["galaxy", "chip", "dimension", "cosmic"],
  },
  {
    id: "cc_black_hole",
    name: "Black Hole",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "rare",
    emoji: "🕳️",
    description: "Everything falls in. Even luck. Even chips. (Mostly luck.)",
    priceChips: 300,
    supply: -1,
    power: { type: "chips_bonus", label: "Singularity", value: 200, description: "Activate for +200 chips — pulled from the void" },
    tags: ["black hole", "space", "rare", "mystery"],
  },
  {
    id: "cc_supernova",
    name: "Supernova Burst",
    collection: "Cosmic Casino",
    collectionId: "cosmic_casino",
    rarity: "rare",
    emoji: "💥",
    description: "A star's final moment — brighter than a billion suns.",
    priceChips: 275,
    supply: -1,
    power: { type: "multiplier_boost", label: "Supernova", value: 150, description: "Activate for a +150 chip burst" },
    tags: ["supernova", "star", "explosion", "rare"],
  },

  // ══════════════════════════════════════════════════════════
  // STREET KINGS — urban art, graffiti, streetwear
  // ══════════════════════════════════════════════════════════
  {
    id: "sk_spray_can",
    name: "Chrome Spray Can",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "common",
    emoji: "🎨",
    description: "Leave your mark on the wall. Street art for the digital age.",
    priceChips: 8,
    supply: -1,
    power: null,
    tags: ["graffiti", "art", "street", "urban"],
  },
  {
    id: "sk_snapback",
    name: "Gold Snapback",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "common",
    emoji: "🧢",
    description: "Worn brim-flat. Certified street royalty.",
    priceChips: 10,
    supply: -1,
    power: null,
    tags: ["cap", "streetwear", "fashion", "urban"],
  },
  {
    id: "sk_boom_box",
    name: "Old School Boombox",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "common",
    emoji: "📻",
    description: "Blasting beats on the corner since '88. A legend in the hood.",
    priceChips: 12,
    supply: -1,
    power: null,
    tags: ["music", "street", "boombox", "retro"],
  },
  {
    id: "sk_microphone",
    name: "Legendary Mic",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "common",
    emoji: "🎤",
    description: "Dropped after the last verse. The crowd went wild. So will your chips.",
    priceChips: 9,
    supply: -1,
    power: null,
    tags: ["mic", "music", "hip hop", "street"],
  },
  {
    id: "sk_crown_tag",
    name: "Crown Tag",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "uncommon",
    emoji: "👑",
    description: "Only kings get to leave this tag. Respect is earned.",
    priceChips: 40,
    supply: -1,
    power: { type: "xp_bonus", label: "Street Cred", value: 80, description: "Activate for +80 XP" },
    tags: ["crown", "tag", "king", "graffiti"],
  },
  {
    id: "sk_gold_chain",
    name: "Heavy Gold Chain",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "uncommon",
    emoji: "⛓️",
    description: "24-karat, 3 inches thick. Dripping in status.",
    priceChips: 55,
    supply: -1,
    power: null,
    tags: ["chain", "gold", "bling", "streetwear"],
  },
  {
    id: "sk_dice_tattoo",
    name: "Lucky Dice Tattoo",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "uncommon",
    emoji: "🎰",
    description: "Inked on the forearm. A gambler's oath sealed in skin.",
    priceChips: 45,
    supply: -1,
    power: { type: "free_spin", label: "Tattooed Luck", value: 20, description: "Activate for +20 chip free spin" },
    tags: ["tattoo", "dice", "gambler", "street"],
  },
  {
    id: "sk_sneakers",
    name: "Air Royale Sneakers",
    collection: "Street Kings",
    collectionId: "street_kings",
    rarity: "uncommon",
    emoji: "👟",
    description: "Limited drop. Only 100 pairs made. These are the digital certificate.",
    priceChips: 62,
    supply: -1,
    power: null,
    tags: ["sneakers", "limited", "streetwear", "fashion"],
  },

  // ══════════════════════════════════════════════════════════
  // ANCIENT FORTUNE — ancient artifacts, ALL LIMITED
  // ══════════════════════════════════════════════════════════
  {
    id: "af_clay_tablet",
    name: "Clay Fortune Tablet",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "common",
    emoji: "📜",
    description: "Sumerian clay tablet inscribed with the first recorded gambling odds.",
    priceChips: 30,
    supply: 1000,
    power: null,
    tags: ["sumerian", "tablet", "ancient", "artifact"],
  },
  {
    id: "af_bronze_coin",
    name: "Bronze Oracle Coin",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "common",
    emoji: "🪙",
    description: "Tossed at the Oracle of Delphi. Heads or tails decided empires.",
    priceChips: 25,
    supply: 1000,
    power: null,
    tags: ["coin", "oracle", "ancient", "greek"],
  },
  {
    id: "af_jade_figurine",
    name: "Jade Fortune God",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "common",
    emoji: "🗿",
    description: "Hand-carved from jade by artisans in the Han Dynasty. Cai Shen watches over you.",
    priceChips: 28,
    supply: 1000,
    power: null,
    tags: ["jade", "china", "fortune god", "ancient"],
  },
  {
    id: "af_roman_coin",
    name: "Roman Denarius",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "common",
    emoji: "🪙",
    description: "Silver denarius from the reign of Emperor Augustus. Genuine Roman mint.",
    priceChips: 22,
    supply: 1000,
    power: null,
    tags: ["roman", "coin", "denarius", "ancient"],
  },
  {
    id: "af_pharaoh_amulet",
    name: "Pharaoh's Amulet",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "rare",
    emoji: "𓂀",
    description: "Buried with Ramesses II. Recovered by a treasure hunter in 1923.",
    priceChips: 300,
    supply: 500,
    power: { type: "xp_bonus", label: "Pharaoh's Blessing", value: 300, description: "Activate for +300 XP" },
    tags: ["pharaoh", "egypt", "amulet", "ancient"],
  },
  {
    id: "af_dragon_pearl",
    name: "Dragon Pearl",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "rare",
    emoji: "🐉",
    description: "Chinese legend says it fell from the sky in 200 BC. Infinite luck awaits.",
    priceChips: 400,
    supply: 500,
    power: { type: "chips_bonus", label: "Dragon's Wealth", value: 250, description: "Activate for +250 chips" },
    tags: ["dragon", "china", "pearl", "luck", "ancient"],
  },
  {
    id: "af_golden_scarab",
    name: "Golden Scarab",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "rare",
    emoji: "🪲",
    description: "Sacred beetle of Egypt. Worn by high priests in the temples of Ra.",
    priceChips: 350,
    supply: 500,
    power: null,
    tags: ["scarab", "egypt", "gold", "ancient"],
  },
  {
    id: "af_ancient_die",
    name: "Babylonian Die",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "rare",
    emoji: "🎲",
    description: "The oldest known gaming die. Carved from bone circa 3000 BC.",
    priceChips: 450,
    supply: 500,
    power: { type: "multiplier_boost", label: "Ancient Odds", value: 200, description: "Activate for +200 chip multiplier boost" },
    tags: ["die", "babylon", "ancient", "gaming"],
  },
  {
    id: "af_shaman_drum",
    name: "Shaman's Drum",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "rare",
    emoji: "🥁",
    description: "Used in rituals to call forth spirits of fortune. The beat changes everything.",
    priceChips: 380,
    supply: 500,
    power: { type: "free_spin", label: "Ritual Spin", value: 150, description: "Activate for a +150 chip ritual spin bonus" },
    tags: ["shaman", "drum", "ritual", "spirit", "ancient"],
  },
  {
    id: "af_philosophers_stone",
    name: "Philosopher's Stone",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "epic",
    emoji: "🔮",
    description: "Alchemists sought it for centuries. The one who holds it turns lead to gold.",
    priceChips: 5000,
    supply: 50,
    power: { type: "chips_bonus", label: "Transmutation", value: 1000, description: "Activate for an instant +1000 chip transmutation" },
    tags: ["alchemy", "philosophers", "stone", "legendary", "ancient"],
  },
  {
    id: "af_atlantis_relic",
    name: "Atlantis Relic",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "epic",
    emoji: "🌊",
    description: "Recovered from the ocean floor. Believed to be from the lost city itself.",
    priceChips: 4500,
    supply: 50,
    power: { type: "jackpot_entry", label: "Lost Jackpot", value: 1, description: "Activate to register a jackpot entry" },
    tags: ["atlantis", "ocean", "relic", "lost", "ancient"],
  },
  {
    id: "af_crystal_skull",
    name: "Crystal Skull",
    collection: "Ancient Fortune",
    collectionId: "ancient_fortune",
    rarity: "epic",
    emoji: "💀",
    description: "Thirteen crystal skulls were believed to hold the secrets of the universe. This is one.",
    priceChips: 6000,
    supply: 50,
    power: { type: "multiplier_boost", label: "Skull Boost", value: 1500, description: "Activate for a +1500 chip ancient boost" },
    tags: ["crystal", "skull", "mystery", "ancient", "mayan"],
  },

  // ══════════════════════════════════════════════════════════
  // CYBERPUNK — tech, neon, cyberware
  // ══════════════════════════════════════════════════════════
  {
    id: "cp_neon_die",
    name: "Neon Die",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "uncommon",
    emoji: "🎲",
    description: "LED-infused acrylic. Glows hot pink in the rain-slicked alley.",
    priceChips: 40,
    supply: -1,
    power: null,
    tags: ["dice", "neon", "cyberpunk", "tech"],
  },
  {
    id: "cp_holo_chip",
    name: "Holo-Chip",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "uncommon",
    emoji: "💿",
    description: "Holographic casino chip from Night City's underground circuit.",
    priceChips: 55,
    supply: -1,
    power: { type: "free_spin", label: "Data Spin", value: 35, description: "Activate for a +35 chip data spin" },
    tags: ["holographic", "chip", "cyberpunk", "night city"],
  },
  {
    id: "cp_data_broker",
    name: "Data Broker Badge",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "uncommon",
    emoji: "🪪",
    description: "Access to every underground casino in the city. No questions asked.",
    priceChips: 80,
    supply: -1,
    power: null,
    tags: ["badge", "data", "access", "cyberpunk"],
  },
  {
    id: "cp_visor",
    name: "Tactical Visor",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "uncommon",
    emoji: "🥽",
    description: "HUD overlay that shows the odds of every bet in real time. Legal? Probably.",
    priceChips: 75,
    supply: -1,
    power: null,
    tags: ["visor", "hud", "tech", "cyberpunk"],
  },
  {
    id: "cp_neon_sign",
    name: "Neon Casino Sign",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "uncommon",
    emoji: "🔆",
    description: "Buzzing pink neon spells out JACKPOT. Visible from three blocks away.",
    priceChips: 60,
    supply: -1,
    power: null,
    tags: ["neon", "sign", "casino", "cyberpunk"],
  },
  {
    id: "cp_neural_jack",
    name: "Neural Jack",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "rare",
    emoji: "🔌",
    description: "Plug in directly. Your reflexes are now 3x faster at the table.",
    priceChips: 250,
    supply: -1,
    power: { type: "xp_bonus", label: "Neural Upload", value: 400, description: "Activate for +400 XP direct upload" },
    tags: ["neural", "cyberware", "implant", "cyberpunk"],
  },
  {
    id: "cp_chrome_hand",
    name: "Chrome Hand",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "rare",
    emoji: "🤖",
    description: "Precision-machined. Never shakes. Never folds. Pure chrome resolve.",
    priceChips: 300,
    supply: -1,
    power: { type: "multiplier_boost", label: "Chrome Boost", value: 175, description: "Activate for a +175 chip chrome boost" },
    tags: ["chrome", "hand", "cyberware", "cyberpunk"],
  },
  {
    id: "cp_quantum_card",
    name: "Quantum Playing Card",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "rare",
    emoji: "🃏",
    description: "Simultaneously every card until observed. Quantum mechanics wins again.",
    priceChips: 350,
    supply: -1,
    power: { type: "chips_bonus", label: "Quantum Collapse", value: 300, description: "Activate for +300 chips when the wave function collapses" },
    tags: ["quantum", "card", "science", "cyberpunk"],
  },
  {
    id: "cp_drone",
    name: "Scout Drone",
    collection: "Cyberpunk",
    collectionId: "cyberpunk",
    rarity: "rare",
    emoji: "🚁",
    description: "Miniaturized surveillance drone. Scouts the competition before you bet.",
    priceChips: 220,
    supply: -1,
    power: { type: "xp_bonus", label: "Drone Recon XP", value: 300, description: "Activate for +300 XP from aerial intelligence" },
    tags: ["drone", "scout", "surveillance", "cyberpunk"],
  },

  // ══════════════════════════════════════════════════════════
  // NATURE SPIRITS — elemental, plants, animals
  // ══════════════════════════════════════════════════════════
  {
    id: "ns_fire_spirit",
    name: "Fire Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "🔥",
    description: "A spark of pure elemental fire. It warms cold luck.",
    priceChips: 11,
    supply: -1,
    power: null,
    tags: ["fire", "elemental", "spirit", "nature"],
  },
  {
    id: "ns_water_spirit",
    name: "Water Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "💧",
    description: "Flow like water. Adapt. Win.",
    priceChips: 11,
    supply: -1,
    power: null,
    tags: ["water", "elemental", "spirit", "nature"],
  },
  {
    id: "ns_earth_spirit",
    name: "Earth Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "🪨",
    description: "Solid. Unshakeable. The foundation of a winning streak.",
    priceChips: 11,
    supply: -1,
    power: null,
    tags: ["earth", "elemental", "spirit", "nature"],
  },
  {
    id: "ns_wind_spirit",
    name: "Wind Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "💨",
    description: "Changes direction in a heartbeat. Unpredictable. Free.",
    priceChips: 11,
    supply: -1,
    power: null,
    tags: ["wind", "elemental", "spirit", "nature"],
  },
  {
    id: "ns_butterfly",
    name: "Spirit Butterfly",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "🦋",
    description: "A butterfly that carries wishes between worlds. Handle with care.",
    priceChips: 13,
    supply: -1,
    power: null,
    tags: ["butterfly", "spirit", "wish", "nature"],
  },
  {
    id: "ns_crystal_ball",
    name: "Nature's Crystal",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "common",
    emoji: "🔮",
    description: "Grown underground over a thousand years. See the future within.",
    priceChips: 18,
    supply: -1,
    power: null,
    tags: ["crystal", "nature", "seer", "future"],
  },
  {
    id: "ns_phoenix",
    name: "Phoenix Feather",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "uncommon",
    emoji: "🦅",
    description: "One feather from the eternal bird. Burns and regrows in golden flame.",
    priceChips: 65,
    supply: -1,
    power: { type: "chips_bonus", label: "Phoenix Rise", value: 50, description: "Activate for +50 chips reborn from the ashes" },
    tags: ["phoenix", "feather", "rebirth", "fire"],
  },
  {
    id: "ns_wolf_spirit",
    name: "Wolf Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "uncommon",
    emoji: "🐺",
    description: "Alpha energy. Pack mentality. Instinct-driven winning.",
    priceChips: 50,
    supply: -1,
    power: null,
    tags: ["wolf", "animal", "alpha", "spirit"],
  },
  {
    id: "ns_tree_of_life",
    name: "Tree of Life",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "uncommon",
    emoji: "🌳",
    description: "Ancient oak whose roots touch the underworld and crown reaches the stars.",
    priceChips: 70,
    supply: -1,
    power: { type: "xp_bonus", label: "Deep Roots", value: 150, description: "Activate for +150 XP" },
    tags: ["tree", "life", "nature", "ancient"],
  },
  {
    id: "ns_lightning_bolt",
    name: "Storm Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "uncommon",
    emoji: "⚡",
    description: "Bottled lightning. Strikes at the perfect moment.",
    priceChips: 60,
    supply: -1,
    power: { type: "multiplier_boost", label: "Thunderstruck", value: 60, description: "Activate for +60 chip thunder boost" },
    tags: ["lightning", "storm", "electric", "spirit"],
  },
  {
    id: "ns_mountain_spirit",
    name: "Mountain Spirit",
    collection: "Nature Spirits",
    collectionId: "nature_spirits",
    rarity: "uncommon",
    emoji: "⛰️",
    description: "Ancient and immovable. The mountain spirit has witnessed ten thousand sunrises.",
    priceChips: 48,
    supply: -1,
    power: null,
    tags: ["mountain", "spirit", "ancient", "nature"],
  },

  // ══════════════════════════════════════════════════════════
  // LEGENDS — mythical creatures, ALL LIMITED
  // ══════════════════════════════════════════════════════════
  {
    id: "leg_dragon_lord",
    name: "Dragon Lord",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "🐲",
    description: "The apex predator of the mythical realm. One who commands this dragon, commands fortune itself.",
    priceChips: 3000,
    supply: 50,
    power: { type: "chips_bonus", label: "Dragon's Hoard", value: 800, description: "Activate for +800 chips from the dragon's hoard" },
    tags: ["dragon", "mythical", "legend", "epic"],
  },
  {
    id: "leg_unicorn",
    name: "Golden Unicorn",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "🦄",
    description: "Only the pure of heart — and the big of balance — may behold this mythical beast.",
    priceChips: 2500,
    supply: 50,
    power: { type: "xp_bonus", label: "Pure Light XP", value: 750, description: "Activate for +750 XP from unicorn magic" },
    tags: ["unicorn", "mythical", "pure", "legend"],
  },
  {
    id: "leg_kraken",
    name: "The Kraken",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "🦑",
    description: "Release the Kraken. A leviathan from the deep that swallows entire ships — and bad luck.",
    priceChips: 4000,
    supply: 50,
    power: { type: "multiplier_boost", label: "Kraken's Grasp", value: 600, description: "Activate for a +600 chip tentacle boost" },
    tags: ["kraken", "sea", "monster", "mythical", "legend"],
  },
  {
    id: "leg_griffin",
    name: "Noble Griffin",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "🦁",
    description: "Part eagle, part lion. Guardian of gold and treasure beyond imagining.",
    priceChips: 3500,
    supply: 50,
    power: { type: "jackpot_entry", label: "Griffin's Guard", value: 1, description: "Activate to register a jackpot entry" },
    tags: ["griffin", "guardian", "mythical", "treasure", "legend"],
  },
  {
    id: "leg_medusa",
    name: "Medusa's Gaze",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "🐍",
    description: "Her gaze turns men to stone. Her NFT turns chips to gold.",
    priceChips: 2800,
    supply: 50,
    power: { type: "chips_bonus", label: "Stone to Gold", value: 700, description: "Activate for +700 chips — turned to gold" },
    tags: ["medusa", "snake", "greek", "mythical", "legend"],
  },
  {
    id: "leg_anubis",
    name: "Anubis's Scale",
    collection: "Legends",
    collectionId: "legends",
    rarity: "epic",
    emoji: "⚖️",
    description: "The feather of Ma'at on one side. Your heart on the other. May you be found worthy.",
    priceChips: 3200,
    supply: 50,
    power: { type: "xp_bonus", label: "Judgment XP", value: 900, description: "Activate for +900 XP — judged worthy by Anubis" },
    tags: ["anubis", "egypt", "scale", "mythical", "legend"],
  },
  {
    id: "leg_zeus_bolt",
    name: "Zeus's Thunderbolt",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "⚡",
    description: "Forged by Hephaestus, wielded by Zeus himself. The most powerful weapon in existence.",
    priceChips: 25000,
    supply: 10,
    power: { type: "chips_bonus", label: "Divine Strike", value: 3000, description: "Activate for +3000 chips from the king of gods" },
    tags: ["zeus", "thunder", "god", "legendary", "olympus"],
  },
  {
    id: "leg_poseidon_trident",
    name: "Poseidon's Trident",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "🔱",
    description: "Commands every ocean and every storm. The God of the Sea bends fate at your will.",
    priceChips: 30000,
    supply: 10,
    power: { type: "multiplier_boost", label: "Tidal Force", value: 2000, description: "Activate for a +2000 chip tidal surge" },
    tags: ["poseidon", "trident", "god", "legendary", "ocean"],
  },
  {
    id: "leg_excalibur",
    name: "Excalibur",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "⚔️",
    description: "The sword of the Once and Future King. Only the worthy may pull it from the stone.",
    priceChips: 20000,
    supply: 10,
    power: { type: "xp_bonus", label: "King's Legacy", value: 2500, description: "Activate for +2500 XP — worthy of legend" },
    tags: ["excalibur", "sword", "king", "legendary", "arthurian"],
  },
  {
    id: "leg_mjolnir",
    name: "Mjölnir",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "🔨",
    description: "Thor's enchanted hammer. Whosoever is worthy shall possess the power of Thor.",
    priceChips: 22000,
    supply: 10,
    power: { type: "jackpot_entry", label: "Thunder God Entry", value: 1, description: "Activate to register a jackpot entry — worthy players only" },
    tags: ["mjolnir", "thor", "hammer", "norse", "legendary"],
  },
  {
    id: "leg_phoenix_reborn",
    name: "Phoenix Reborn",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "🦜",
    description: "The eternal bird in its full glory. Every 500 years it rises from its own ashes, more powerful than before.",
    priceChips: 35000,
    supply: 10,
    power: { type: "chips_bonus", label: "Eternal Flame", value: 5000, description: "Activate for +5000 chips — reborn in fire and fortune" },
    tags: ["phoenix", "eternal", "fire", "legendary", "rebirth"],
  },
  {
    id: "leg_loki",
    name: "Loki's Dice",
    collection: "Legends",
    collectionId: "legends",
    rarity: "legendary",
    emoji: "😈",
    description: "The trickster god's personal pair of dice. They always land how Loki intends.",
    priceChips: 40000,
    supply: 10,
    power: { type: "jackpot_entry", label: "Trickster's Entry", value: 1, description: "Activate for a jackpot entry — Loki's favor is unpredictable but powerful" },
    tags: ["loki", "trickster", "norse", "dice", "legendary"],
  },

  // ══════════════════════════════════════════════════════════
  // ONE OF ONE — ultra-rare, supply = 1, rarity = "unique"
  // ══════════════════════════════════════════════════════════
  {
    id: "oo_genesis_card",
    name: "Genesis Card #1",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "✨",
    description: "The very first card ever dealt at Casino Aurelius. There will never be another.",
    priceChips: 100000,
    supply: 1,
    power: { type: "chips_bonus", label: "Genesis Bonus", value: 10000, description: "Activate for an extraordinary +10000 chip genesis bonus" },
    tags: ["genesis", "first", "unique", "historic"],
  },
  {
    id: "oo_casino_key",
    name: "Master Casino Key",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "🗝️",
    description: "Opens every vault, every room. The Master Key of Casino Aurelius. One key. One owner.",
    priceChips: 150000,
    supply: 1,
    power: { type: "jackpot_entry", label: "Master Entry", value: 1, description: "Activate for a jackpot entry — the master player's right" },
    tags: ["key", "master", "vault", "unique", "exclusive"],
  },
  {
    id: "oo_diamond_crown",
    name: "Diamond Crown",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "👑",
    description: "Worn only by the greatest. 74 flawless diamonds set in 24-karat gold. One crown. One king.",
    priceChips: 200000,
    supply: 1,
    power: { type: "chips_bonus", label: "Crown Jewels", value: 15000, description: "Activate for +15000 chips — the royal prerogative" },
    tags: ["crown", "diamond", "king", "unique", "royalty"],
  },
  {
    id: "oo_the_ace",
    name: "The Ace",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "🃏",
    description: "Hand-painted by a master artist on real playing card stock. Unmatched. Unmistakable.",
    priceChips: 120000,
    supply: 1,
    power: { type: "multiplier_boost", label: "The Ace Play", value: 8000, description: "Activate for a +8000 chip ace multiplier" },
    tags: ["ace", "painted", "art", "unique", "masterpiece"],
  },
  {
    id: "oo_casino_chip_1",
    name: "Chip #1 — Signed",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "🥇",
    description: "Casino chip #1, signed by the founder. The literal first chip of Casino Aurelius. Irreplaceable.",
    priceChips: 500000,
    supply: 1,
    power: { type: "xp_bonus", label: "Founder's Gift", value: 10000, description: "Activate for +10000 XP — the founder's personal gift" },
    tags: ["chip", "signed", "founder", "unique", "genesis"],
  },
  {
    id: "oo_golden_ticket",
    name: "Golden Ticket",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "🎫",
    description: "There is one golden ticket. Whoever finds it wins a lifetime of luck.",
    priceChips: 250000,
    supply: 1,
    power: { type: "jackpot_entry", label: "Golden Entry", value: 1, description: "Activate for a jackpot entry — the golden right" },
    tags: ["golden", "ticket", "unique", "jackpot", "rare"],
  },
  {
    id: "oo_black_card",
    name: "The Black Card",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "⬛",
    description: "No limit. No questions. The Black Card has no equal. Given to one player. Ever.",
    priceChips: 750000,
    supply: 1,
    power: { type: "chips_bonus", label: "No Limit Bonus", value: 25000, description: "Activate for +25000 chips — no limit, no questions" },
    tags: ["black card", "no limit", "unique", "exclusive", "elite"],
  },
  {
    id: "oo_casino_deed",
    name: "Casino Deed",
    collection: "One of One",
    collectionId: "one_of_one",
    rarity: "unique",
    emoji: "📃",
    description: "The deed to Casino Aurelius. You now own the house. The house always wins.",
    priceChips: 1000000,
    supply: 1,
    power: { type: "multiplier_boost", label: "House Edge", value: 20000, description: "Activate for +20000 chips — the house advantage is yours" },
    tags: ["deed", "casino", "owner", "unique", "ultimate"],
  },
];
