export interface ScratchTicket {
  id: string;
  name: string;
  emoji: string;
  description: string;
  priceChips: number; // cost to buy (in chips)
  maxPrize: number;   // max possible prize in chips
  theme: string;
  prizes: ScratchPrize[];
}

export interface ScratchPrize {
  chips: number;   // 0 means no win
  label: string;
  weight: number;  // higher = more likely
}

// ─── Lucky Gems (10 tickets, priceChips 5–500) ───────────────────────────────

const luckyGems: ScratchTicket[] = [
  {
    id: "gem-001",
    name: "Ruby Rush",
    emoji: "💎",
    description: "Ruby-red luck — match three rubies for a blazing payout!",
    priceChips: 5,
    maxPrize: 50,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,  label: "No Win",       weight: 55 },
      { chips: 5,  label: "Chip Back",     weight: 20 },
      { chips: 10, label: "Ruby Shard",    weight: 12 },
      { chips: 20, label: "Ruby Gem",      weight: 7  },
      { chips: 35, label: "Ruby Cluster",  weight: 4  },
      { chips: 50, label: "Ruby Jackpot!", weight: 2  },
    ],
  },
  {
    id: "gem-002",
    name: "Sapphire Spin",
    emoji: "💎",
    description: "Cool blue sapphires hiding sky-high prizes.",
    priceChips: 10,
    maxPrize: 120,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 55 },
      { chips: 10,  label: "Chip Back",        weight: 18 },
      { chips: 20,  label: "Sapphire Shard",   weight: 12 },
      { chips: 45,  label: "Sapphire Gem",     weight: 8  },
      { chips: 80,  label: "Sapphire Star",    weight: 5  },
      { chips: 120, label: "Sapphire Jackpot!",weight: 2  },
    ],
  },
  {
    id: "gem-003",
    name: "Emerald Empire",
    emoji: "💎",
    description: "Green fortune awaits in the emerald realm.",
    priceChips: 20,
    maxPrize: 250,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,   label: "No Win",           weight: 52 },
      { chips: 20,  label: "Chip Back",         weight: 18 },
      { chips: 40,  label: "Emerald Shard",     weight: 13 },
      { chips: 80,  label: "Emerald Gem",       weight: 9  },
      { chips: 150, label: "Emerald Crown",     weight: 5  },
      { chips: 250, label: "Emerald Emperor!",  weight: 3  },
    ],
  },
  {
    id: "gem-004",
    name: "Diamond Dazzle",
    emoji: "💎",
    description: "Only the purest diamonds unlock true riches.",
    priceChips: 30,
    maxPrize: 400,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,   label: "No Win",            weight: 50 },
      { chips: 30,  label: "Chip Back",          weight: 18 },
      { chips: 60,  label: "Diamond Dust",       weight: 13 },
      { chips: 120, label: "Diamond Chip",       weight: 10 },
      { chips: 250, label: "Diamond Ring",       weight: 6  },
      { chips: 400, label: "Diamond Dazzle!",    weight: 3  },
    ],
  },
  {
    id: "gem-005",
    name: "Amethyst Ascent",
    emoji: "💎",
    description: "Climb the amethyst tower to legendary wins.",
    priceChips: 50,
    maxPrize: 600,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,   label: "No Win",            weight: 50 },
      { chips: 50,  label: "Chip Back",          weight: 17 },
      { chips: 100, label: "Amethyst Shard",     weight: 12 },
      { chips: 200, label: "Amethyst Gem",       weight: 10 },
      { chips: 400, label: "Amethyst Aura",      weight: 7  },
      { chips: 600, label: "Amethyst Ascent!",   weight: 4  },
    ],
  },
  {
    id: "gem-006",
    name: "Opal Oracle",
    emoji: "💎",
    description: "Opals reveal the future — and your fortune.",
    priceChips: 75,
    maxPrize: 900,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 50 },
      { chips: 75,  label: "Chip Back",        weight: 16 },
      { chips: 150, label: "Opal Glimmer",     weight: 12 },
      { chips: 300, label: "Opal Gem",         weight: 10 },
      { chips: 600, label: "Opal Vision",      weight: 8  },
      { chips: 900, label: "Opal Oracle!",     weight: 4  },
    ],
  },
  {
    id: "gem-007",
    name: "Topaz Treasure",
    emoji: "💎",
    description: "Golden topaz stones guard ancient treasure.",
    priceChips: 100,
    maxPrize: 1200,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,    label: "No Win",           weight: 48 },
      { chips: 100,  label: "Chip Back",         weight: 17 },
      { chips: 200,  label: "Topaz Shard",       weight: 12 },
      { chips: 400,  label: "Topaz Gem",         weight: 10 },
      { chips: 800,  label: "Topaz Chest",       weight: 8  },
      { chips: 1200, label: "Topaz Treasure!",   weight: 5  },
    ],
  },
  {
    id: "gem-008",
    name: "Garnet Galaxy",
    emoji: "💎",
    description: "Deep red garnets from the stars above.",
    priceChips: 150,
    maxPrize: 1800,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,    label: "No Win",          weight: 47 },
      { chips: 150,  label: "Chip Back",        weight: 17 },
      { chips: 300,  label: "Garnet Star",      weight: 12 },
      { chips: 600,  label: "Garnet Nebula",    weight: 10 },
      { chips: 1200, label: "Garnet Supernova", weight: 9  },
      { chips: 1800, label: "Garnet Galaxy!",   weight: 5  },
    ],
  },
  {
    id: "gem-009",
    name: "Pearl Pinnacle",
    emoji: "💎",
    description: "Rare pearls from the deep — worth their weight in gold.",
    priceChips: 250,
    maxPrize: 3000,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,    label: "No Win",          weight: 45 },
      { chips: 250,  label: "Chip Back",        weight: 17 },
      { chips: 500,  label: "Pearl Luster",     weight: 12 },
      { chips: 1000, label: "Pearl Gem",        weight: 11 },
      { chips: 2000, label: "Pearl Crown",      weight: 10 },
      { chips: 3000, label: "Pearl Pinnacle!",  weight: 5  },
    ],
  },
  {
    id: "gem-010",
    name: "Crystal Crown",
    emoji: "💎",
    description: "The grandest gem of all — the Crystal Crown awaits royalty.",
    priceChips: 500,
    maxPrize: 6000,
    theme: "Lucky Gems",
    prizes: [
      { chips: 0,    label: "No Win",           weight: 43 },
      { chips: 500,  label: "Chip Back",         weight: 17 },
      { chips: 1000, label: "Crystal Shard",     weight: 13 },
      { chips: 2000, label: "Crystal Gem",       weight: 12 },
      { chips: 4000, label: "Crystal Throne",    weight: 10 },
      { chips: 6000, label: "Crystal Crown!",    weight: 5  },
    ],
  },
];

// ─── Casino Classic (10 tickets, priceChips 10–1000) ─────────────────────────

const casinoClassic: ScratchTicket[] = [
  {
    id: "cc-001",
    name: "Aces High",
    emoji: "🃏",
    description: "Four aces — pure classic casino power!",
    priceChips: 10,
    maxPrize: 100,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,   label: "No Win",         weight: 55 },
      { chips: 10,  label: "Pair",           weight: 18 },
      { chips: 25,  label: "Two Pair",       weight: 12 },
      { chips: 50,  label: "Three of a Kind",weight: 8  },
      { chips: 75,  label: "Full House",     weight: 5  },
      { chips: 100, label: "Aces High!",     weight: 2  },
    ],
  },
  {
    id: "cc-002",
    name: "Royal Flush Rush",
    emoji: "🃏",
    description: "Chase the royal flush for the ultimate payout.",
    priceChips: 25,
    maxPrize: 300,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,   label: "No Win",      weight: 52 },
      { chips: 25,  label: "Chip Back",   weight: 18 },
      { chips: 50,  label: "High Card",   weight: 13 },
      { chips: 100, label: "Flush",       weight: 9  },
      { chips: 200, label: "Straight",    weight: 5  },
      { chips: 300, label: "Royal Flush!",weight: 3  },
    ],
  },
  {
    id: "cc-003",
    name: "Lucky Sevens",
    emoji: "🃏",
    description: "777 — the luckiest number in the casino.",
    priceChips: 50,
    maxPrize: 600,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,   label: "No Win",       weight: 50 },
      { chips: 50,  label: "Chip Back",    weight: 17 },
      { chips: 100, label: "One 7",        weight: 13 },
      { chips: 200, label: "Two 7s",       weight: 10 },
      { chips: 400, label: "Three 7s",     weight: 7  },
      { chips: 600, label: "777 Jackpot!", weight: 3  },
    ],
  },
  {
    id: "cc-004",
    name: "Black Jack Bonanza",
    emoji: "🃏",
    description: "Hit 21 and watch the chips pile up.",
    priceChips: 75,
    maxPrize: 900,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,   label: "Bust",          weight: 50 },
      { chips: 75,  label: "Chip Back",     weight: 17 },
      { chips: 150, label: "17–18",         weight: 13 },
      { chips: 300, label: "19–20",         weight: 10 },
      { chips: 600, label: "Blackjack",     weight: 7  },
      { chips: 900, label: "Perfect 21!",   weight: 3  },
    ],
  },
  {
    id: "cc-005",
    name: "Joker's Wild",
    emoji: "🃏",
    description: "The joker brings chaos — and incredible luck.",
    priceChips: 100,
    maxPrize: 1200,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,    label: "No Win",        weight: 48 },
      { chips: 100,  label: "Chip Back",     weight: 17 },
      { chips: 200,  label: "One Joker",     weight: 13 },
      { chips: 400,  label: "Two Jokers",    weight: 11 },
      { chips: 800,  label: "Joker Trio",    weight: 8  },
      { chips: 1200, label: "Jokers Wild!",  weight: 3  },
    ],
  },
  {
    id: "cc-006",
    name: "Poker Face",
    emoji: "🃏",
    description: "Keep your poker face and rake in the pot.",
    priceChips: 150,
    maxPrize: 1800,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,    label: "Folded",        weight: 47 },
      { chips: 150,  label: "Chip Back",     weight: 17 },
      { chips: 300,  label: "Bluff Win",     weight: 13 },
      { chips: 600,  label: "Value Bet",     weight: 11 },
      { chips: 1200, label: "Pot Taken",     weight: 8  },
      { chips: 1800, label: "Poker Ace!",    weight: 4  },
    ],
  },
  {
    id: "cc-007",
    name: "Spades Supreme",
    emoji: "🃏",
    description: "The Ace of Spades rules the classic game.",
    priceChips: 200,
    maxPrize: 2400,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,    label: "No Win",         weight: 46 },
      { chips: 200,  label: "Chip Back",      weight: 17 },
      { chips: 400,  label: "Spade Trick",    weight: 13 },
      { chips: 800,  label: "Spade Slam",     weight: 11 },
      { chips: 1600, label: "Ace of Spades",  weight: 8  },
      { chips: 2400, label: "Spades Supreme!",weight: 5  },
    ],
  },
  {
    id: "cc-008",
    name: "Hearts on Fire",
    emoji: "🃏",
    description: "Red hearts burning bright with passion and prizes.",
    priceChips: 300,
    maxPrize: 3600,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,    label: "No Win",         weight: 45 },
      { chips: 300,  label: "Chip Back",      weight: 17 },
      { chips: 600,  label: "Heart Flame",    weight: 13 },
      { chips: 1200, label: "Heart Blaze",    weight: 11 },
      { chips: 2400, label: "Heart Inferno",  weight: 9  },
      { chips: 3600, label: "Hearts on Fire!",weight: 5  },
    ],
  },
  {
    id: "cc-009",
    name: "Diamond Suite",
    emoji: "🃏",
    description: "The diamond suite — where fortunes are made.",
    priceChips: 500,
    maxPrize: 6000,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,    label: "No Win",          weight: 43 },
      { chips: 500,  label: "Chip Back",       weight: 17 },
      { chips: 1000, label: "Diamond Cut",     weight: 13 },
      { chips: 2000, label: "Diamond Suite",   weight: 12 },
      { chips: 4000, label: "Diamond Royale",  weight: 10 },
      { chips: 6000, label: "Diamond Flush!",  weight: 5  },
    ],
  },
  {
    id: "cc-010",
    name: "Grand Slam",
    emoji: "🃏",
    description: "The grandest classic of them all — go for the Grand Slam!",
    priceChips: 1000,
    maxPrize: 12000,
    theme: "Casino Classic",
    prizes: [
      { chips: 0,     label: "No Win",         weight: 40 },
      { chips: 1000,  label: "Chip Back",      weight: 17 },
      { chips: 2000,  label: "Small Slam",     weight: 14 },
      { chips: 4000,  label: "Slam Bonus",     weight: 13 },
      { chips: 8000,  label: "Full Slam",      weight: 11 },
      { chips: 12000, label: "Grand Slam!",    weight: 5  },
    ],
  },
];

// ─── Fortune Dragons (10 tickets, priceChips 20–2000) ────────────────────────

const fortuneDragons: ScratchTicket[] = [
  {
    id: "fd-001",
    name: "Baby Dragon",
    emoji: "🐉",
    description: "Even the youngest dragon breathes lucky fire.",
    priceChips: 20,
    maxPrize: 200,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 53 },
      { chips: 20,  label: "Chip Back",        weight: 18 },
      { chips: 40,  label: "Dragon Ember",     weight: 12 },
      { chips: 80,  label: "Dragon Flame",     weight: 9  },
      { chips: 140, label: "Dragon Fire",      weight: 5  },
      { chips: 200, label: "Baby Dragon!",     weight: 3  },
    ],
  },
  {
    id: "fd-002",
    name: "Jade Dragon",
    emoji: "🐉",
    description: "The jade dragon brings harmony and prosperity.",
    priceChips: 40,
    maxPrize: 480,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 52 },
      { chips: 40,  label: "Chip Back",        weight: 17 },
      { chips: 80,  label: "Jade Scale",       weight: 12 },
      { chips: 160, label: "Jade Fang",        weight: 10 },
      { chips: 320, label: "Jade Claw",        weight: 6  },
      { chips: 480, label: "Jade Dragon!",     weight: 3  },
    ],
  },
  {
    id: "fd-003",
    name: "Golden Dragon",
    emoji: "🐉",
    description: "The golden dragon reigns supreme over fortune.",
    priceChips: 60,
    maxPrize: 720,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 51 },
      { chips: 60,  label: "Chip Back",        weight: 17 },
      { chips: 120, label: "Gold Scale",       weight: 12 },
      { chips: 240, label: "Gold Fang",        weight: 10 },
      { chips: 480, label: "Gold Horn",        weight: 7  },
      { chips: 720, label: "Golden Dragon!",   weight: 3  },
    ],
  },
  {
    id: "fd-004",
    name: "Azure Dragon",
    emoji: "🐉",
    description: "The azure dragon of the east — master of luck.",
    priceChips: 80,
    maxPrize: 960,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,   label: "No Win",          weight: 50 },
      { chips: 80,  label: "Chip Back",        weight: 17 },
      { chips: 160, label: "Azure Scale",      weight: 12 },
      { chips: 320, label: "Azure Fang",       weight: 10 },
      { chips: 640, label: "Azure Wing",       weight: 8  },
      { chips: 960, label: "Azure Dragon!",    weight: 3  },
    ],
  },
  {
    id: "fd-005",
    name: "Shadow Dragon",
    emoji: "🐉",
    description: "From the shadows emerges limitless power.",
    priceChips: 100,
    maxPrize: 1200,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,    label: "No Win",          weight: 48 },
      { chips: 100,  label: "Chip Back",        weight: 17 },
      { chips: 200,  label: "Shadow Scale",     weight: 13 },
      { chips: 400,  label: "Shadow Fang",      weight: 11 },
      { chips: 800,  label: "Shadow Roar",      weight: 8  },
      { chips: 1200, label: "Shadow Dragon!",   weight: 3  },
    ],
  },
  {
    id: "fd-006",
    name: "Crimson Dragon",
    emoji: "🐉",
    description: "Blood-red scales and a roar that shakes the mountains.",
    priceChips: 200,
    maxPrize: 2400,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,    label: "No Win",           weight: 47 },
      { chips: 200,  label: "Chip Back",         weight: 17 },
      { chips: 400,  label: "Crimson Scale",     weight: 13 },
      { chips: 800,  label: "Crimson Fang",      weight: 11 },
      { chips: 1600, label: "Crimson Roar",      weight: 8  },
      { chips: 2400, label: "Crimson Dragon!",   weight: 4  },
    ],
  },
  {
    id: "fd-007",
    name: "Storm Dragon",
    emoji: "🐉",
    description: "The storm dragon commands thunder, lightning, and riches.",
    priceChips: 400,
    maxPrize: 4800,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,    label: "No Win",           weight: 45 },
      { chips: 400,  label: "Chip Back",         weight: 17 },
      { chips: 800,  label: "Storm Scale",       weight: 13 },
      { chips: 1600, label: "Thunder Strike",    weight: 12 },
      { chips: 3200, label: "Lightning Roar",    weight: 8  },
      { chips: 4800, label: "Storm Dragon!",     weight: 5  },
    ],
  },
  {
    id: "fd-008",
    name: "Celestial Dragon",
    emoji: "🐉",
    description: "Divine essence of the heavens — celestial rewards.",
    priceChips: 600,
    maxPrize: 7200,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,    label: "No Win",            weight: 44 },
      { chips: 600,  label: "Chip Back",          weight: 17 },
      { chips: 1200, label: "Celestial Scale",    weight: 13 },
      { chips: 2400, label: "Celestial Fang",     weight: 12 },
      { chips: 4800, label: "Celestial Roar",     weight: 9  },
      { chips: 7200, label: "Celestial Dragon!",  weight: 5  },
    ],
  },
  {
    id: "fd-009",
    name: "Eternal Dragon",
    emoji: "🐉",
    description: "The eternal dragon has guarded treasure since time began.",
    priceChips: 1000,
    maxPrize: 12000,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,     label: "No Win",           weight: 42 },
      { chips: 1000,  label: "Chip Back",         weight: 17 },
      { chips: 2000,  label: "Eternal Scale",     weight: 13 },
      { chips: 4000,  label: "Eternal Fang",      weight: 13 },
      { chips: 8000,  label: "Eternal Roar",      weight: 10 },
      { chips: 12000, label: "Eternal Dragon!",   weight: 5  },
    ],
  },
  {
    id: "fd-010",
    name: "Dragon Emperor",
    emoji: "🐉",
    description: "Only the Dragon Emperor holds the ultimate fortune.",
    priceChips: 2000,
    maxPrize: 24000,
    theme: "Fortune Dragons",
    prizes: [
      { chips: 0,     label: "No Win",             weight: 40 },
      { chips: 2000,  label: "Chip Back",           weight: 17 },
      { chips: 4000,  label: "Emperor's Scale",     weight: 14 },
      { chips: 8000,  label: "Emperor's Fang",      weight: 13 },
      { chips: 16000, label: "Emperor's Roar",      weight: 11 },
      { chips: 24000, label: "Dragon Emperor!",     weight: 5  },
    ],
  },
];

// ─── Space Jackpot (10 tickets, priceChips 50–5000) ──────────────────────────

const spaceJackpot: ScratchTicket[] = [
  {
    id: "sj-001",
    name: "Star Dust",
    emoji: "🚀",
    description: "Scattered stardust from the cosmos — each speck is lucky.",
    priceChips: 50,
    maxPrize: 500,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,   label: "Black Hole",      weight: 52 },
      { chips: 50,  label: "Chip Back",        weight: 18 },
      { chips: 100, label: "Star Dust",        weight: 13 },
      { chips: 200, label: "Shooting Star",    weight: 9  },
      { chips: 350, label: "Meteor Strike",    weight: 5  },
      { chips: 500, label: "Star Dust Win!",   weight: 3  },
    ],
  },
  {
    id: "sj-002",
    name: "Lunar Launch",
    emoji: "🚀",
    description: "Blast off to the moon for spectacular prizes.",
    priceChips: 75,
    maxPrize: 750,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,   label: "No Launch",        weight: 50 },
      { chips: 75,  label: "Chip Back",         weight: 18 },
      { chips: 150, label: "Lunar Orbit",       weight: 13 },
      { chips: 300, label: "Moon Landing",      weight: 10 },
      { chips: 550, label: "Lunar Base",        weight: 6  },
      { chips: 750, label: "Lunar Launch!",     weight: 3  },
    ],
  },
  {
    id: "sj-003",
    name: "Nebula Riches",
    emoji: "🚀",
    description: "A dazzling nebula swirling with cosmic wealth.",
    priceChips: 100,
    maxPrize: 1200,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "Dark Matter",     weight: 50 },
      { chips: 100,  label: "Chip Back",        weight: 17 },
      { chips: 200,  label: "Nebula Cloud",     weight: 13 },
      { chips: 400,  label: "Nebula Core",      weight: 10 },
      { chips: 800,  label: "Nebula Star",      weight: 7  },
      { chips: 1200, label: "Nebula Jackpot!",  weight: 3  },
    ],
  },
  {
    id: "sj-004",
    name: "Alien Artifact",
    emoji: "🚀",
    description: "Alien technology holds prizes beyond imagination.",
    priceChips: 150,
    maxPrize: 1800,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "No Signal",        weight: 48 },
      { chips: 150,  label: "Chip Back",         weight: 17 },
      { chips: 300,  label: "Alien Relic",       weight: 13 },
      { chips: 600,  label: "Alien Tech",        weight: 11 },
      { chips: 1200, label: "Alien Device",      weight: 8  },
      { chips: 1800, label: "Alien Artifact!",   weight: 3  },
    ],
  },
  {
    id: "sj-005",
    name: "Black Hole Bonus",
    emoji: "🚀",
    description: "What goes in... massive prizes come out!",
    priceChips: 200,
    maxPrize: 2400,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "Void",              weight: 47 },
      { chips: 200,  label: "Chip Back",          weight: 17 },
      { chips: 400,  label: "Event Horizon",      weight: 13 },
      { chips: 800,  label: "Singularity",        weight: 11 },
      { chips: 1600, label: "Black Hole Burst",   weight: 8  },
      { chips: 2400, label: "Black Hole Bonus!",  weight: 4  },
    ],
  },
  {
    id: "sj-006",
    name: "Supernova Strike",
    emoji: "🚀",
    description: "When a star dies, riches are born.",
    priceChips: 300,
    maxPrize: 3600,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "Cold Space",        weight: 46 },
      { chips: 300,  label: "Chip Back",          weight: 17 },
      { chips: 600,  label: "Nova Spark",         weight: 13 },
      { chips: 1200, label: "Supernova Flash",    weight: 12 },
      { chips: 2400, label: "Supernova Wave",     weight: 8  },
      { chips: 3600, label: "Supernova Strike!",  weight: 4  },
    ],
  },
  {
    id: "sj-007",
    name: "Galaxy Galore",
    emoji: "🚀",
    description: "Billions of stars, billions of chips to win.",
    priceChips: 500,
    maxPrize: 6000,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "Empty Space",       weight: 44 },
      { chips: 500,  label: "Chip Back",          weight: 17 },
      { chips: 1000, label: "Galaxy Edge",        weight: 13 },
      { chips: 2000, label: "Galaxy Core",        weight: 12 },
      { chips: 4000, label: "Galactic Center",    weight: 9  },
      { chips: 6000, label: "Galaxy Galore!",     weight: 5  },
    ],
  },
  {
    id: "sj-008",
    name: "Pulsar Prize",
    emoji: "🚀",
    description: "Pulsars pulse with regular bursts of jackpot energy.",
    priceChips: 750,
    maxPrize: 9000,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,    label: "Static",            weight: 43 },
      { chips: 750,  label: "Chip Back",          weight: 17 },
      { chips: 1500, label: "Pulsar Blip",        weight: 13 },
      { chips: 3000, label: "Pulsar Pulse",       weight: 12 },
      { chips: 6000, label: "Pulsar Burst",       weight: 10 },
      { chips: 9000, label: "Pulsar Prize!",      weight: 5  },
    ],
  },
  {
    id: "sj-009",
    name: "Quasar Quest",
    emoji: "🚀",
    description: "The brightest objects in the universe — quasar prizes.",
    priceChips: 1500,
    maxPrize: 18000,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,     label: "Dark Matter",       weight: 41 },
      { chips: 1500,  label: "Chip Back",          weight: 17 },
      { chips: 3000,  label: "Quasar Glow",        weight: 13 },
      { chips: 6000,  label: "Quasar Beam",        weight: 13 },
      { chips: 12000, label: "Quasar Blast",       weight: 11 },
      { chips: 18000, label: "Quasar Quest!",      weight: 5  },
    ],
  },
  {
    id: "sj-010",
    name: "Cosmic Jackpot",
    emoji: "🚀",
    description: "The ultimate space prize — the Cosmic Jackpot is yours to claim!",
    priceChips: 5000,
    maxPrize: 60000,
    theme: "Space Jackpot",
    prizes: [
      { chips: 0,     label: "Void",              weight: 38 },
      { chips: 5000,  label: "Chip Back",          weight: 17 },
      { chips: 10000, label: "Cosmic Ray",         weight: 14 },
      { chips: 20000, label: "Cosmic Wave",        weight: 14 },
      { chips: 40000, label: "Cosmic Storm",       weight: 12 },
      { chips: 60000, label: "Cosmic Jackpot!",    weight: 5  },
    ],
  },
];

// ─── Golden Gods (10 tickets, priceChips 100–10000) ──────────────────────────

const goldenGods: ScratchTicket[] = [
  {
    id: "gg-001",
    name: "Hermes Herald",
    emoji: "⚡",
    description: "Swift as Hermes — quick wins delivered to your door.",
    priceChips: 100,
    maxPrize: 1000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "No Blessing",      weight: 50 },
      { chips: 100,  label: "Chip Back",         weight: 17 },
      { chips: 200,  label: "Hermes' Coin",      weight: 13 },
      { chips: 400,  label: "Hermes' Caduceus",  weight: 10 },
      { chips: 700,  label: "Hermes' Wings",     weight: 7  },
      { chips: 1000, label: "Hermes Herald!",    weight: 3  },
    ],
  },
  {
    id: "gg-002",
    name: "Athena's Wisdom",
    emoji: "⚡",
    description: "Wisdom of Athena reveals the path to prosperity.",
    priceChips: 200,
    maxPrize: 2000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "No Wisdom",         weight: 49 },
      { chips: 200,  label: "Chip Back",          weight: 17 },
      { chips: 400,  label: "Owl's Eye",          weight: 13 },
      { chips: 800,  label: "Athena's Shield",    weight: 11 },
      { chips: 1400, label: "Athena's Spear",     weight: 7  },
      { chips: 2000, label: "Athena's Wisdom!",   weight: 3  },
    ],
  },
  {
    id: "gg-003",
    name: "Poseidon's Trident",
    emoji: "⚡",
    description: "Control the seas with Poseidon's legendary trident.",
    priceChips: 250,
    maxPrize: 3000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "Undercurrent",       weight: 48 },
      { chips: 250,  label: "Chip Back",           weight: 17 },
      { chips: 500,  label: "Sea Foam",            weight: 13 },
      { chips: 1000, label: "Wave Surge",          weight: 11 },
      { chips: 2000, label: "Ocean's Might",       weight: 8  },
      { chips: 3000, label: "Poseidon's Trident!", weight: 3  },
    ],
  },
  {
    id: "gg-004",
    name: "Ares' Fury",
    emoji: "⚡",
    description: "Battle like Ares — conquer the odds and claim glory.",
    priceChips: 300,
    maxPrize: 3600,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "Retreat",            weight: 47 },
      { chips: 300,  label: "Chip Back",           weight: 17 },
      { chips: 600,  label: "Battle Cry",          weight: 13 },
      { chips: 1200, label: "War Shield",          weight: 11 },
      { chips: 2400, label: "Ares' Sword",         weight: 9  },
      { chips: 3600, label: "Ares' Fury!",         weight: 3  },
    ],
  },
  {
    id: "gg-005",
    name: "Apollo's Arrow",
    emoji: "⚡",
    description: "Apollo never misses — and neither will you.",
    priceChips: 400,
    maxPrize: 4800,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "Missed Shot",         weight: 46 },
      { chips: 400,  label: "Chip Back",            weight: 17 },
      { chips: 800,  label: "Arrow Nock",           weight: 13 },
      { chips: 1600, label: "Golden Arrow",         weight: 11 },
      { chips: 3200, label: "Apollo's Bullseye",    weight: 9  },
      { chips: 4800, label: "Apollo's Arrow!",      weight: 4  },
    ],
  },
  {
    id: "gg-006",
    name: "Hades' Hoard",
    emoji: "⚡",
    description: "Descend into the underworld to claim hidden treasures.",
    priceChips: 500,
    maxPrize: 6000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "Lost Souls",          weight: 45 },
      { chips: 500,  label: "Chip Back",            weight: 17 },
      { chips: 1000, label: "Shade's Coin",         weight: 13 },
      { chips: 2000, label: "Underworld Gold",      weight: 12 },
      { chips: 4000, label: "Cerberus' Hoard",      weight: 9  },
      { chips: 6000, label: "Hades' Hoard!",        weight: 4  },
    ],
  },
  {
    id: "gg-007",
    name: "Dionysus Delight",
    emoji: "⚡",
    description: "Revelry, wine, and mountains of golden chips.",
    priceChips: 750,
    maxPrize: 9000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,    label: "Sober Loss",           weight: 44 },
      { chips: 750,  label: "Chip Back",             weight: 17 },
      { chips: 1500, label: "Festival Grape",        weight: 13 },
      { chips: 3000, label: "Wine Amphora",          weight: 12 },
      { chips: 6000, label: "Bacchic Frenzy",        weight: 10 },
      { chips: 9000, label: "Dionysus Delight!",     weight: 4  },
    ],
  },
  {
    id: "gg-008",
    name: "Hephaestus Forge",
    emoji: "⚡",
    description: "Forge your destiny with Hephaestus and earn divine riches.",
    priceChips: 1000,
    maxPrize: 12000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,     label: "Cold Anvil",          weight: 43 },
      { chips: 1000,  label: "Chip Back",            weight: 17 },
      { chips: 2000,  label: "Spark",                weight: 13 },
      { chips: 4000,  label: "Forged Blade",         weight: 13 },
      { chips: 8000,  label: "Divine Armor",         weight: 10 },
      { chips: 12000, label: "Hephaestus Forge!",    weight: 4  },
    ],
  },
  {
    id: "gg-009",
    name: "Zeus Thunderstruck",
    emoji: "⚡",
    description: "The king of gods commands lightning and colossal wins.",
    priceChips: 2500,
    maxPrize: 30000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,     label: "Lightning Miss",       weight: 40 },
      { chips: 2500,  label: "Chip Back",             weight: 17 },
      { chips: 5000,  label: "Thunder Clap",          weight: 14 },
      { chips: 10000, label: "Lightning Strike",      weight: 13 },
      { chips: 20000, label: "Zeus' Bolt",            weight: 11 },
      { chips: 30000, label: "Zeus Thunderstruck!",   weight: 5  },
    ],
  },
  {
    id: "gg-010",
    name: "Olympus Jackpot",
    emoji: "⚡",
    description: "Scale Mount Olympus itself for the divine jackpot.",
    priceChips: 10000,
    maxPrize: 120000,
    theme: "Golden Gods",
    prizes: [
      { chips: 0,      label: "Mortal Defeat",       weight: 38 },
      { chips: 10000,  label: "Chip Back",            weight: 17 },
      { chips: 20000,  label: "Olympian Trial",       weight: 14 },
      { chips: 40000,  label: "Olympian Champion",    weight: 14 },
      { chips: 80000,  label: "God's Blessing",       weight: 12 },
      { chips: 120000, label: "Olympus Jackpot!",     weight: 5  },
    ],
  },
];

export const SCRATCH_CATALOG: ScratchTicket[] = [
  ...luckyGems,
  ...casinoClassic,
  ...fortuneDragons,
  ...spaceJackpot,
  ...goldenGods,
];

export function getTicketById(id: string): ScratchTicket | undefined {
  return SCRATCH_CATALOG.find((t) => t.id === id);
}
